name: Sync to GitLab

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name preshcode007
          git config --global user.email okiemenprecious@gmail.com

      - name: Mirror to GitLab
        run: |
          git remote add target https://gitlab.com/okiemenprecious/onadata-project.git
          git fetch --verbose -pPtfu --progress --show-forced-updates origin
          git push --verbose --progress --prune --follow-tags target
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
